---
- name: download custom metric file
  get_url:
    url: https://aws-cloudwatch.s3.amazonaws.com/downloads/{{ file_cm }}
    #dest: /home/ec2-user/CloudWatchMonitoringScripts-1.2.2.zip
    dest: /home/ec2-user/{{ file_cm }}
    mode: 0440
    owner: ec2-user
    group: ec2-user

- name: unzip custom metric file
  unarchive:
    src: /home/ec2-user/{{ file_cm }}
    dest: /home/ec2-user
    remote_src: yes

- name: Create cronjob custom metric
  cron:
    name: "send memory disk metric to cloudwatch"
    user: "ec2-user"
    minute: "*/5"
    job: "/home/ec2-user/cloudwatch/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --from-cron"

