---

# Install perl packages
- name: install perl packages for amazon linux 
  yum:
    name: "{{ item.name }}" 
    state: latest
  with_items:
    - { name: perl-Switch }
    - { name: perl-DateTime }
    - { name: perl-Sys-Syslog }
    - { name: perl-LWP-Protocol-https }
    - { name: perl-Digest-SHA.x86_64 }
  become: yes
  become_user: root
  when:
    - ansible_facts['distribution'] == "Amazon"

- name: install perl packages for suse linux
  zypper:
    name: "{{ item.name }}"
    state: latest
  with_items:
    - { name: perl-Switch }
    - { name: perl-DateTime }
    - { name: "perl(LWP::Protocol::https)" }
  become: yes
  become_user: root
  when:
    - ansible_facts['distribution'] == "SLES"



- name: download custom metric file
  get_url:
    url: https://aws-cloudwatch.s3.amazonaws.com/downloads/{{ file_cm }}
    #dest: /home/ec2-user/CloudWatchMonitoringScripts-1.2.2.zip
    dest: /home/ec2-user/{{ file_cm }}
    mode: 0440
    owner: ec2-user
    #group: ec2-user

- name: unzip custom metric file
  unarchive:
    src: /home/ec2-user/{{ file_cm }}
    dest: /home/ec2-user
    remote_src: yes

- name: Create cronjob custom metric for amazon linux
  cron:
    name: "send memory disk metric to cloudwatch"
    user: "ec2-user"
    minute: "*/5"
    job: "/home/ec2-user/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --from-cron"
  when:
    - ansible_facts['distribution'] == "Amazon"

- name: Create cronjob custom metric for suse linux
  cron:
    name: "send memory disk metric to cloudwatch"
    user: "ec2-user"
    minute: "*/5"
    job: "/home/ec2-user/aws-scripts-mon/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --disk-path=/sapcd --disk-path=/sapmnt --disk-path=/usr/sap --disk-path=/usr/sap/trans --from-cron"
  when:
    - ansible_facts['distribution'] == "SLES"
