---
- name: Install Java 1.8
  yum: 
    name: java-1.8.0-openjdk
    state: present

- name: Download Tomcat 8.5.x
  get_url:
    url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/{{ tomcat_file }}.tar.gz
    dest: /home/ec2-user            
    mode: 0440
    owner: ec2-user
    group: ec2-user            

- name: Create tomcat root folder
  file:
    path: /home/webservices
    state: directory
    owner: ec2-user
    group: ec2-user            
    mode: 0755

- name: Unzip Tomcat
  unarchive:
    src: /home/ec2-user/{{ tomcat_file }}.tar.gz
    dest: /home/webservices
    remote_src: yes 
    owner: ec2-user
    group: ec2-user            

  #- name: Change tomcat port
  #  template:
  #    src: "tomcat-server.xml.j2"
  #    dest: "/opt/{{ tomcat_file }}/conf/server.xml"

- name: Create symbolic link           
  file:
    src: /home/webservices/{{ tomcat_file }}
    dest: /home/webservices/gict_prd
    state: link
    owner: ec2-user
    group: ec2-user            

- name: Create tomcat web root
  file:
    path: /home/webservices/gict_webroot
    state: directory
    owner: ec2-user
    group: ec2-user            
    mode: 0755
