---
- name: Install Java 1.8
  yum: name=java-1.8.0-openjdk state=present

- name: Download Tomcat 8.5.x
  get_url:
    url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.9/bin/apache-tomcat-8.5.9.tar.gz
    dest: /home/ec2-user            
    mode: 0440
    owner: ec2-user
    group: ec2-user            

- name: Unzip Tomcat
  unarchive:
    src: /home/ec2-user/apache-tomcat-8.5.9.tar.gz
    dest: /opt
    remote_src: yes 
    owner: ec2-user
    group: ec2-user            

- name: Create symbolic link           
  file:
    src: /opt/apache-tomcat-8.5.9
    dest: /usr/share/tomcat
    state: link
